---
- name: User Management Playbook
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Ensure the groups exist
      ansible.builtin.group:
        name: "{{ item.key }}"
        state: "{{ item.value.state | default('present') }}"
      loop: "{{ users | dict2items }}"

    - name: Ensure the users exist
      ansible.builtin.user:
        name: "{{ item.key }}"
        password: "{{ item.value.password}}"
        groups: "{{ item.key }}"
        shell: "/bin/bash"
        state: "{{ item.value.state | default('present') }}"
        append: yes
      loop: "{{ users | dict2items }}"
      notify:
        - Add users to sudo group

    - name: Ensure proper permissions for home directory
      ansible.builtin.file:
        path: "/home/{{ item.key }}"
        state: directory
        owner: "{{ item.key }}"
        group: "{{ item.key}}"
        mode: '0700'
      when: item.value.state == 'present'
      loop: "{{ users | dict2items }}"

    - name: Ensure SSH directory exists
      ansible.builtin.file:
        path: "/home/{{ item.key }}/.ssh"
        state: directory
        owner: "{{ item.key }}"
        group: "{{ item.key }}"
        mode: '0700'
      when: item.value.state == 'present'
      loop: "{{ users | dict2items }}"

    - name: Add authorized key for user
      ansible.builtin.copy:
        dest: "/home/{{ item.key }}/.ssh/authorized_keys"
        content: "{{ item.value.ssh_public_key }}"
        owner: "{{ item.key }}"
        group: "{{ item.key }}"
        mode: '0600'
      when: item.value.state == 'present'
      loop: "{{ users | dict2items }}"

    - name: Add users into sudoers for no password
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ item.key }}"
        content: "{{ item.key }} ALL=(ALL) NOPASSWD:ALL"
        mode: '0440'
      when: item.value.sudo_no_password | default(false)
      loop: "{{ users | dict2items }}"

    - name: Delete home directory if user removed
      ansible.builtin.file:
        path: "/home/{{ item.key }}"
        state: absent
        owner: "{{ item.key }}"
        group: "{{ item.key }}"
        mode: '0700'
      when: item.value.state == 'absent'
      loop: "{{ users | dict2items }}"

    - name: Delete sudoers file if user removed
      ansible.builtin.file:
        path: "/etc/sudoers.d/{{ item.key }}"
        state: absent
      when: item.value.state == 'absent'
      loop: "{{ users | dict2items }}"

  handlers:
    - name: Add users to sudo group
      ansible.builtin.user:
        name: "{{ item.key }}"
        groups: "sudo"
        append: yes
      when: item.value.sudo | default(false)
      loop: "{{ users | dict2items }}"
