---
users:
  abhishekn:
    state: present
    sudo: true
    password: "$6$WizkZE2P./BYN4d8$oRCGzFa2N5t7oa9pAkGTjK6QUgydJYNwGhTJr0j6yzJIluZPY5pW9rnLqseJnTEDtkQBI4hlcB6qBnGDJ/vwr/"
    ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCpIh6M1P/02LmmocKN6hkHwM+jhcjISAz44ao0cPNDPNrHmj+wCDTUGo7utn+IPPFGq7wqV543uuet8ZaEtPk+QHgPd1vrT871bc1FEm9in5IvXn9QqJIxvIz/5EtZxmyj5N41yf1tWtdPnHWX7vWz+FfGeLZgXZLiAHDx3OTUxOFaAHcLeSCrZKAG1avaeXygiLAczWY09klDb+QFPIvvnls81r/e1xvbH3QoxlJXsOiogVYB+qioNVFveMlLJQHTB4SrHPr9UkxK2m6ylrVeo28GJiexHRW6rvBPKiMixrsfqKXxJH/ohgFGGHr/AHp7H5N0EtYH3ITkHKtvX2UtLgczwdApnPLb4VUXb5ZjjQUz1SPODaucX23S30ieeoZQGMXID0BBeTnQ/aX2c6DXV9IDw/dgyO53s9TLUPpS95LH7h8pfCbWltZhsUuEqsjahaihHCyWwnrGtF5WonA8vjrhBrAfWN157XIKB68bhzqa8meR+8LSiayKFIslf7Rw5qkEESSPftY4KL5js5Iggk3LZI6XDJ9HPdfdxD89VLn4agStYI0cIYV038OqvB10TEMZRohs2NoAsLyXmHFKNiDMzXJCkhiLyNEdYNmUI3TMC5/IPz3FmvnRgrVcb2LxP6v8jyd5c56yDKJKsQ5N67PGK8VQ31tlIib2MrNa0Q== abhishek.nagesh@tarento.com"
